name: Günlük Feribot Saatleri Güncelleme

on:
  schedule:
    - cron: '0 4 * * *'  # Her sabah 06:00'da çalıştır (UTC)
  workflow_dispatch:  # Manuel çalıştırmayı etkinleştir

jobs:
  update_schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerekli Paketleri Kur
        run: pip install requests beautifulsoup4

      - name: Feribot Saatlerini Güncelle
        run: python ferry.py  

      - name: Değişiklikleri Kaydet ve Gönder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/umtksa/ferry.git
          git add .
          git commit -m "Güncellenmiş feribot saatleri (Automated)" || exit 0
          git push origin main
